Linux & Windows workflows

diff --git a/.github/workflows/ci-linux.yml b/.github/workflows/ci-linux.yml
--- a/.github/workflows/ci-linux.yml
+++ b/.github/workflows/ci-linux.yml
@@ -21,8 +21,8 @@ permissions:
   contents: read
 
 jobs:
-  build-linux:
-    name: Build on Linux
+  linux-build:
+    name: Linux Build
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -37,6 +37,7 @@ jobs:
         uses: jwlawson/actions-setup-cmake@v1
         with:
           cmake-version: '3.22.0'
+          
 
       - name: Install Required Packages (Linux)
         run: |
@@ -66,7 +67,19 @@ jobs:
             libssl-dev \
             libffi-dev \
             libltdl-dev \
-            libibus-1.0-dev || echo "Some packages could not be installed, proceeding anyway."
+            libibus-1.0-dev \
+            
+            libasound2-dev \
+            libpulse-dev \
+            libx11-dev \
+            libxft-dev \
+            libxext-dev \
+            libwayland-dev \
+            libxkbcommon-dev \
+            libegl1-mesa-dev \
+            libibus-1.0-dev \
+            mesa-common-dev \
+            libgl1-mesa-dev || echo "Some packages could not be installed, proceeding anyway."
 
       - name: Cache vcpkg and Dependencies
         uses: actions/cache@v3
@@ -94,10 +107,7 @@ jobs:
       - name: Install Dependencies via vcpkg (Manifest Mode)
         run: |
           export CFLAGS="-D_strnicmp=strncasecmp -I/usr/include/audio -I/opt/vc/include $CFLAGS"
-          export CXXFLAGS="-D_strnicmp=strncasecmp -I/usr/include/audio -I/opt/vc/include $CXXFLAGS"
-          
-          sudo apt-get update
-          sudo apt-get install -y libasound2-dev libpulse-dev libx11-dev libibus-1.0-dev mesa-common-dev libgl1-mesa-dev
+          export CXXFLAGS="-D_strnicmp=strncasecmp -I/usr/include/audio -I/opt/vc/include $CXXFLAGS" 
           
           RETRIES=3
           for i in $(seq 1 $RETRIES); do
